# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # or 'pip', 'go', 'maven', etc.
    directory: '/' # Root directory where dependencies are located
    schedule:
      interval: 'daily' # How often to check for updates
    target-branch: 'main' # Default branch for updates

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'daisyui'
